#!/usr/bin/env python3
"""
generate_tool.py

Part of the automated micro-SaaS factory. Picks a random micro-tool idea
from a hardcoded list, asks Gemini to write a complete single-page web app
(Tailwind CSS via CDN + vanilla JS) for it, and saves the result to
app/index.html.

Requires:
    pip install google-genai

Environment variables:
    GEMINI_API_KEY - your Gemini API key
"""

import os
import random
import re
import sys
from pathlib import Path

from google import genai

MODEL_NAME = "gemini-3.5-flash"
OUTPUT_DIR = Path("app")
OUTPUT_FILE = OUTPUT_DIR / "index.html"

# Hardcoded list of micro-tool ideas. Extend this over time, or replace it
# with a smarter idea-generation step later.
TOOL_IDEAS = [
    "Freelance Hourly Rate Calculator",
    "SaaS Churn Calculator",
    "Simple Pomodoro Timer",
    "Tip Splitter Calculator",
    "Unit Converter (Length, Weight, Temperature)",
    "Password Strength Checker",
    "Word & Character Counter",
    "Countdown Timer for Events",
    "Loan Payoff Calculator",
    "Habit Streak Tracker",
]


def build_prompt(tool_name: str) -> str:
    """Build the instruction prompt sent to Gemini for a given tool idea."""
    return f"""You are an expert front-end engineer. Build a complete, production-quality, \
single-page web application called "{tool_name}".

Requirements:
- Output ONE self-contained HTML file. Do not use separate CSS or JS files.
- Include Tailwind CSS via the CDN script tag \
(<script src="https://cdn.tailwindcss.com"></script>) for all styling. Use a \
clean, modern, mobile-responsive design with sensible spacing and a card-based layout.
- All application logic must be vanilla JavaScript inside a single <script> \
tag near the end of the <body>. No frameworks, no build step, no external JS \
libraries other than the Tailwind CDN script.
- The app must be fully functional in the browser with no backend or server \
calls of any kind.
- Include a clear heading, a one-line description of what the tool does, \
well-labeled form inputs, basic input validation, sensible default values, \
and a visible results area that updates on user interaction.
- Add a small footer note reading "Generated by an AI micro-SaaS factory".
- Do not include any placeholder or TODO comments -- the app must be complete and working.
- Return ONLY the raw HTML for the file, starting with <!DOCTYPE html> and \
ending with </html>. Do not wrap it in Markdown code fences and do not \
include any commentary before or after the code.
"""


def extract_html(text: str) -> str:
    """Strip Markdown code fences in case the model adds them anyway."""
    text = text.strip()
    fence_match = re.match(r"^```(?:html)?\s*\n?(.*?)\n?```$", text, re.DOTALL)
    if fence_match:
        text = fence_match.group(1).strip()
    return text


def main() -> None:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY environment variable is not set.", file=sys.stderr)
        sys.exit(1)

    tool_name = random.choice(TOOL_IDEAS)
    print(f"Selected micro-tool idea: {tool_name}")

    client = genai.Client(api_key=api_key)
    prompt = build_prompt(tool_name)

    print(f"Requesting {MODEL_NAME} to generate the app...")
    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt,
    )

    if not response.text:
        print("ERROR: Received an empty response from Gemini.", file=sys.stderr)
        sys.exit(1)

    html_output = extract_html(response.text)

    if not html_output.lower().startswith("<!doctype html"):
        print(
            "WARNING: model output did not start with <!DOCTYPE html>; "
            "saving it anyway for manual review.",
            file=sys.stderr,
        )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(html_output, encoding="utf-8")
    print(f"Saved generated app to {OUTPUT_FILE} ({len(html_output)} characters).")

    # Record which idea was picked so the workflow can reference it (e.g. in the PR body).
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a", encoding="utf-8") as f:
            f.write(f"tool_idea={tool_name}\n")


if __name__ == "__main__":
    main()
